[package]
name = "rust-lil-examples"
version = "0.1.0"
authors = ["backskin <backskin@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#
#[lib]
#name = "_ffi"
#crate-type = ["dylib"]
